services:
  frontend:
    volumes:
      - sv:/frontend
    container_name: notes-wasm-app
    build: ./
    restart: always
    ports:
      - 5173:5173
    stdin_open: true

  cors_proxy:
    volumes:
      - sv:/proxy
    build: ./proxy/
    restart: always
    ports:
      - 8081:8081

volumes:
  sv:
